[package]
name = "osm-rail-route"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.8", features = ["derive"] }
osmpbfreader = { git = "https://github.com/TeXitoi/osmpbfreader-rs.git" }
serde_json = { version = "1.0" }
